- name: Elasticsearch
  debug:
    msg: "Elasticsearch"

- name: run elasticsearch container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elk_version }}
    volumes:
      - "data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    env:
      discovery.type: "single-node"
