- name: install plex media server
  debug:
    msg: "please update me"

- name: run plex media server conainer
  docker_container:
    name: 'plex'
    #image: 'plexinc/pms-docker'
    state: 'started'
    image: 'plexinc/pms-docker'
    network_mode: 'bridge' 
    labels: "traefik.http.routers.plex-server.rule=Host(`localhost`)"
    restart: yes
    state: started
    volumes:
      - /home/deploy/docker/plex/config:/config
      - /home/deploy/docker/plex/transcode:/transcode
      - /home/deploy/docker/plex/media:/media
      - /home/deploy/docker/plex/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env:
      TZ: "America/New_York"
      HOSTNAME: "docker-plex"
      #PLEX_CLAIM: "claim-BajZHbSb5TpoPFuRRQYz"
      PLEX_UID: "1000"
      PLEX_GID: "1000"
      ADVERTISE_IP: "http://192.168.0.42:32400/"
      USERDIR: "/home/deploy/docker"

