- name: Elasticsearch
  debug:
    msg: "Elasticsearch"

- name: create elk network
  docker_network:
    name: elastic
    driver: overlay

- name: run elasticsearch container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elk_version }}
    volumes:
      - "data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - name: elastic
    env:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

- name: run logstash continer
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:{{ elk_version }}
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    env:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - name: elastic

- name: run kibana container
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:{{ elk_version }}
    ports:
      - "5601:5601"
    networks:
      - name: elastic
